./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p0 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p1 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p2 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p3 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p4 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p5 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p6 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p7 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p8 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p9 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p10 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p11 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p12 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p13 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p14 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p15 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p16 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p17 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p18 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p19 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p20 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p21 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p22 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p23 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p24 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p25 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p26 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p27 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p28 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p29 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p30 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p31 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p32 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p33 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p34 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p35 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p36 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p37 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p38 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p39 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p40 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p41 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p42 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p43 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p44 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p45 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p46 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p47 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p48 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p49 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p50 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p51 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p52 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p53 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p54 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p55 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p56 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p57 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p58 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p59 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p60 DataDecoder 0
./submit_ToolAnalysis_job.sh /pnfs/annie/persistent/users/mnieslon/data/rawdata/RAWDataR2281S0p61 DataDecoder 0
